title: Mine Reclamation and Closure
name: Mine Reclamation and Closure
description: >
  This is a page and blog about all things mine reclamation and closure, life-of mine reclamation and closure cost estimates, financial assurance estimates (bonds), and asset retirement obligation estimates for mining.
url: "https://pitsunda.github.io"  # the base hostname & protocol for your site
baseurl: ""  # the subpath of your site, e.g. /blog if your blog is not at the root of your site

github_username: pitsunda

# Build settings
markdown: kramdown
theme: minima  # Uncomment this if you want to use the minima theme, or specify another theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# jekyll-paginate configuration
paginate: 10  # Posts per page
paginate_path: "/page:num/"  # Paginate path, ensure this matches the structure of your blog URLs

exclude:
  - Gemfile
  - Gemfile.lock

permalink: /posts/:title/  # Permalinks pattern for posts
excerpt_separator: <!--more-->  # Separator for excerpts
author: https://www.linkedin.com/in/filiz-t-3a309442/  # Author information

# Additional configurations
host: 0.0.0.0  # Host IP for the Jekyll server (used when serving the site locally)
