# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
#  - name: Featured Projects
 #   submenu:
  #    - name: MicroBam
   #     link: /projects/microbam
    #  - name: OurLegacy
     #   link: /projects/ourlegacy
  - name: Home
    link: /
  - name: Blog
    link: /posts
  - name: Resources
    link: /resources
  - name: Services
    link: /services
  - name: Contact  
    link: /contact
